version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  rabbit:
    image: rabbitmq
    depends_on:
      - db
  company_tasks:
    build: .
    command: >
      bash -c "pip install psycopg2-binary &&
               pip install -r pip_requirements.txt &&
               python manage.py migrate &&
               python manage.py shell -c \"from company_tasks.utils import create_admin; create_admin('admin', 'admin@example.com', 'admin')\" &&
               celery -A company_tasks worker -l info -B --detach &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db