version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
    depends_on:
      - db
  company_tasks:
    build: .
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver &&
               celery -A company_tasks worker -l info -B"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbit